/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.1.0/samples
 */
 
plugins {
    java
    eclipse
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
	implementation("com.mysql:mysql-connector-j:8.3.0")
	implementation("org.flywaydb:flyway-core:11.14.1")
	implementation("org.flywaydb:flyway-mysql:11.14.1")
	implementation("net.datafaker:datafaker:2.4.4")
	
	compileOnly("org.projectlombok:lombok:1.18.42")
	annotationProcessor("org.projectlombok:lombok:1.18.42")
}

tasks.test {
    useJUnitPlatform()
}

